-- 02_auth_columns.sql — runs after migrations + seed.
-- Supabase kept credentials in auth.users and never gave guru/santri a password
-- column. The Go backend issues its own JWTs, so the bcrypt hash lives on the
-- profile row instead. Added here rather than as a Supabase migration because
-- deployed migrations are immutable.

alter table public.guru   add column if not exists password text;
alter table public.santri add column if not exists password text;

-- Bootstrap admin. Password: admin123 — change on first login.
-- Hash is generated by pgcrypto at init time (bcrypt cost 12, $2a$ prefix) so it
-- is always valid for golang.org/x/crypto/bcrypt instead of a hardcoded literal.
-- ponytail: single bootstrap admin, no invite flow. Add one when there's a
-- second person who needs to create accounts.
insert into auth.users (id, email)
values ('a1fa7a10-0000-0000-0000-000000000001', 'admin@sdnbaturaja.sch.id')
on conflict (id) do update set email = excluded.email;

insert into public.guru (id, nama, email, status, roles, password)
values (
  'a1fa7a10-0000-0000-0000-000000000001',
  'Administrator',
  'admin@sdnbaturaja.sch.id',
  'active',
  array['Admin'],
  extensions.crypt('admin123', extensions.gen_salt('bf', 12))
)
on conflict (id) do update set
  email    = excluded.email,
  status   = 'active',
  roles    = excluded.roles,
  password = excluded.password;

insert into public.user_profiles (id, role, display_name, email, status)
values (
  'a1fa7a10-0000-0000-0000-000000000001',
  'admin',
  'Administrator',
  'admin@sdnbaturaja.sch.id',
  'active'
)
on conflict (id) do update set
  role         = 'admin',
  display_name = excluded.display_name,
  email        = excluded.email,
  status       = 'active';
