-- 02_auth_columns.sql — runs after migrations + seed.
--
-- Kolom `password` pada guru dan santri TIDAK lagi dibuat di sini. Berkas ini
-- berjalan sesudah seluruh migrasi, sementara migrasi 20260823000200 dan
-- 20260823000300 sudah menyetel `santri.password` — sehingga membuat kolomnya di
-- sini membuat setiap pemasangan baru gagal di tengah jalan. Kolomnya kini
-- dibuat migrasi 20260624000310, yang berjalan tepat sesudah tabelnya ada.
-- Lihat catatan lengkapnya di berkas migrasi itu.
--
-- Yang tersisa di sini hanya akun admin bootstrap, yang memang harus dibuat
-- SESUDAH seed supaya tidak tertimpa data contoh.

-- Bootstrap admin. Password: admin123 — change on first login.
-- Hash is generated by pgcrypto at init time (bcrypt cost 12, $2a$ prefix) so it
-- is always valid for golang.org/x/crypto/bcrypt instead of a hardcoded literal.
-- ponytail: single bootstrap admin, no invite flow. Add one when there's a
-- second person who needs to create accounts.
insert into auth.users (id, email)
values ('a1fa7a10-0000-0000-0000-000000000001', 'admin@sdnbaturaja.sch.id')
on conflict (id) do update set email = excluded.email;

insert into public.guru (id, nama, email, status, roles, password)
values (
  'a1fa7a10-0000-0000-0000-000000000001',
  'Administrator',
  'admin@sdnbaturaja.sch.id',
  'active',
  array['Admin'],
  extensions.crypt('admin123', extensions.gen_salt('bf', 12))
)
on conflict (id) do update set
  email    = excluded.email,
  status   = 'active',
  roles    = excluded.roles,
  password = excluded.password;

insert into public.user_profiles (id, role, display_name, email, status)
values (
  'a1fa7a10-0000-0000-0000-000000000001',
  'admin',
  'Administrator',
  'admin@sdnbaturaja.sch.id',
  'active'
)
on conflict (id) do update set
  role         = 'admin',
  display_name = excluded.display_name,
  email        = excluded.email,
  status       = 'active';
